[shell]
program = "/bin/zsh"

[colors.primary]
background = "#111011"

[font.normal]
family = "Berkeley Mono"
style = "Regular"

[font]
size = 12.0

[window]
dynamic_padding = false
opacity = 1

[window.padding]
x = 0
y = 0
